version: '3.7'

services:
  serverside_1:
    environment:
      - ASPNETCORE_URLS=http://+:80
      - redisUrl=redis
    image: ${DOCKER_REGISTRY-}serverside
    container_name: server_1
    build:
      context: .
      dockerfile: ServerSide/Dockerfile
    ports:
      - "90:80"
    restart: unless-stopped
    depends_on:
      - redis

  serverside_2:
    environment:
      - ASPNETCORE_URLS=http://+:80
      - redisUrl=redis
    image: ${DOCKER_REGISTRY-}serverside
    container_name: server_2
    build:
      context: .
      dockerfile: ServerSide/Dockerfile
    ports:
      - "95:80"
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:5.0.6
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"